### ISSUE TITLE
Unknown XML-RPC tag 'TITLE'

### ISSUE THREAD

**Issue by eibrahim** [scottgonzalez/node-wordpress#17]
I run this in a loop to create multiple posts, it works fine for maybe 3 to 6 posts and then it starts erroring out with 

`Unknown XML-RPC tag 'TITLE'`

Any idea?

**Comment by scottgonzalez** [comment]
This happens when the server has an error and responds with an HTML error page instead of sending an error through XML-RPC. I should see if I can detect this inside the module and convert it to a nicer error.

If this is happening consistently for you, you may have a problem with how you're making the calls. Are you able to create a reduced test case that reliably shows the problem?

**Comment by eibrahim** [comment]
It turns out the statusCode was 418 which was because of the mod_security settings at dreamhost... there is more info at http://wiki.dreamhost.com/Mod_security and https://wordpress.org/support/topic/live-writer-418-unused-server-error

I guess it is not your code but I wish the message was more informative :)  Thanks for this great utility.

**Comment by scottgonzalez** [comment]
v1.2.1 now includes the HTTP status code and status message if the server response is not an XML-RPC response.
