### ISSUE TITLE
WordPress autop

### ISSUE THREAD

**Issue by joeauty** [scottgonzalez/node-wordpress#9]
Hello,

I'm trying to enable paragraphs appearing in returned content via this simple plugin that filters the content through WP's autop function:

https://github.com/chrisguitarguy/WPSE-Plugins/blob/master/xmlrpc-autop.php

With this plugin enabled these calls fail. Might this be a sanitization issue? Before I mess around, I'm wondering if anybody has tried to enable paragraphs with your fine module?

**Comment by scottgonzalez** [comment]
What do you mean by "these calls fail"? Are you calling the custom method directly?

**Comment by joeauty** [comment]
Sorry for my lack of clarity. getPosts fails, I haven't tested any other method provided by this module. With this plugin enabled, I get the following response:

{ [Error: XML-RPC fault: server error. requested method wp.getPosts does not exist.]
code: -32601,
faultCode: -32601,
faultString: 'server error. requested method wp.getPosts does not exist.' }

With this plugin disabled this method works as advertised. My primary objective here is to fetch content with paragraphs left intact.

**Comment by scottgonzalez** [comment]
So wen you enable the autop plugin, then the standard XML-RPC methods fail? If so, that sounds like a problem with the autop plugin.

**Comment by joeauty** [comment]
Yeah, although I'm wondering if this is simply a sanitization issue. Could HTML tags being included in a Javascript object be causing parse errors?

**Comment by scottgonzalez** [comment]
HTML in a JavaScript object would never be a problem, because JavaScript doesn't care about that. But you're not even getting to that point. If the problem was sanitization, it'd be a problem at the XML-RPC layer, not the JavaScript layer, and if that was the case it would mean that the autop plugin just doesn't work because it's generating garbage output.

However, the error message makes it pretty clear that the method does not exist, not that there was an error in the method call. Considering the fact that `node-wordpress` doesn't modify WordPress in any way, I'd say this is definitely a problem with the autop plugin. I don't see why the autop plugin would break the existing methods though, since it's properly adding to the array, not overwriting it.
